### ISSUE TITLE
Crash with Patchouli

### ISSUE THREAD

**Issue by TheButterbrotMan** [ArtixAllMighty/PublicGuiAnnouncement#11]
https://bytebin.lucko.me/O9lleHQiLV

**Comment by ArtixAllMighty** [comment]
Hi ! some mod seems to have an issue with mixins,
which paintings ++ ~~does not use !~~  uses one of, and it is called ScreenAccessor.
Are you positive paintings++ is the cause ?
would you mind installing [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) ? It makes fabric crash logs a bit more readable, so I can determine what class that mixins is trying to be applied on. 

> org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found

**Comment by AbsolemJackdaw** [comment]
Hi ! some mod seems to have an issue with mixins,
PGa uses a couple, but none of them are named 'net.fabricmc.example.mixin.ExampleMixin'
Are you positive PGA is the cause ?
would you mind installing [Not Enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes) ? It makes fabric crash logs a bit more readable, so I can determine what class that mixins is trying to be applied on.

> org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: The specified mixin 'net.fabricmc.example.mixin.ExampleMixin' was not found

**Comment by TheButterbrotMan** [comment]
Its allready installed.

**Comment by TheButterbrotMan** [comment]
So it crashes right after starting client.

**Comment by AbsolemJackdaw** [comment]
I might know where this is comming from. i'm going to investigate

**Comment by AbsolemJackdaw** [comment]
I have investigated and wasn't able to reproduce the issue. 

So removing either patchouli or pga will result in the game working ?

**Comment by AbsolemJackdaw** [comment]
crashes similar have been posted. 
related to a mixin targeting class_310

currently removing tags for 1.18.2 on .1 files
I will be uploading a fabric mod compiled against 1.18.2 *today*

consider this issue fixed. 
if any crash does happen again, do come back. 
the local tests executed where inconclusive towards crashing
