### ISSUE TITLE
Rendering causes huge loss in FPS with shaderpacks (custom lighting rendering kills game's speed with the interface).

### ISSUE THREAD

**Issue by MinerB4** [ArtixAllMighty/PublicGuiAnnouncement#14]
I usually play Minecraft with shaders, it's the best way for me to have fun. However, every time I open up any inventory/interface the game start to lag heavily, I have tested by disabling the mod and it does not do this. I don't know what could be done to fix this, but if there is something that can be done about it I would greatly appreciate it.

**Comment by AbsolemJackdaw** [comment]
While I definitely would want to help, optifine isn't known to be compatible with a lot of mods in various ways. 

I could look into my rendering code again, or ask friends to check for me, to make sure I do not make any weird mistakes anywhere could be on the table, but I've got a feeling the issue likely lies by optifine. 

Could i ask you for your specs, as well as what modloader and version you are using ?

**Comment by MinerB4** [comment]
**Forge 40.1.0** for **Minecraft 1.18.2**
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: AMD Radeon(TM) Graphics
Allocated: 6124MB (Mem: 7200MB)
**Optifine HD H7 Ultra**

**Comment by AbsolemJackdaw** [comment]
thanks, i'll see if I can do anything, if at all

**Comment by MinerB4** [comment]
I did actually discover that using the Iris Shaders and Sodium mod did not have this issue.  The game ran very smoothly and all user-interface interactions did not cause any issues.

So the issue resides with how Optifine handled the mod.

*The Fabric version which has Iris Shaders and Sodium

**Comment by AbsolemJackdaw** [comment]
I'm closing the issue with the conclusion that optifine brakes yet another mod.
