### ISSUE TITLE
Request for Compatibility for mods [Fabric/Forge]

### ISSUE THREAD

**Issue by SpiderKolo** [ArtixAllMighty/PublicGuiAnnouncement#15]
I came here to suggest few mods for compatibility.
All of the mentioned mods will be on Fabric (my preferred modloader) with few also being on Forge.

Most of the listed mods introduce new GUI for many of their interactions. I don't expect that all of them get their compatibility as there is a good chance that at least some mod authors will be against compatibility. I also understand that it might take time for something like this to happen.

I never tested any of the mods with this one, but I did checked the list of compatible mods and those were not mentioned on it.

Here is a list of said mods:

**Completely new GUI:**
**Fabric:**
Origins
Biome Makeover
Map Atlases [Fabric]
Create Fabric

**Forge:**
Origins (Forge)
Biome Makeover (Forge)
Map Atlases [Forge]
Create

**Both:**
Simple Voice Chat

**Reused GUI from vanilla system (as far as I know/think):**
**Villager Trading GUI:**
**Fabric:**
Goblin Traders Fabric
End Goblin Traders Fabric
Lava Java

**(Possibly, needs testing) GUI from Double Chest:**
**Fabric:**
Probably Chests

**(Possibly, needs testing) GUI from Single Chest:**
**Fabric:**
Chest Cavity

I might later on add few more mods to the list either in separate comment OR make a new request in case I find more of the mods... if that's not a problem for you. 😄
Have a nice day!

**Comment by AbsolemJackdaw** [comment]
Hey, theres no need to ask me for compatibility ! These compats are resourcepack driven and can be easily made by the end user !

**Comment by AbsolemJackdaw** [comment]
https://github.com/ArtixAllMighty/PublicGuiAnnouncement/wiki/Add-Mod-Compatibility
