### ISSUE TITLE
Custom texture pack results in skewed images.

### ISSUE THREAD

**Issue by forthwist** [ArtixAllMighty/PublicGuiAnnouncement#16]
Hi there!  I made a first stab at a thought bubble texture pack:  
[Boxy Bubbles ](https://www.curseforge.com/minecraft/texture-packs/public-gui-announcement-icon-set)
( https://www.curseforge.com/minecraft/texture-packs/public-gui-announcement-icon-set )

But I've run into an issue.  The various existing GUI images are all different sizes, so when I try to use uniform 256x256 images they get scaled differently and don't appear inside the thought bubble properly.  I tried to compensate for the translation happening to the bubbles, but cant account for the non uniform scaling--it looks like crap, halp.

**Comment by AbsolemJackdaw** [comment]
Oh boy someones making a reskin ! :0
Ill look into the issue as soon as I can. Currently on a holiday !

**Comment by AbsolemJackdaw** [comment]
First thing I can think of is making a resourcepack that overrides the shipped values for the image sizes ? 

https://github.com/ArtixAllMighty/PublicGuiAnnouncement/wiki/Add-Mod-Compatibility

https://github.com/ArtixAllMighty/PublicGuiAnnouncement/blob/1.19/Common/src/main/resources/assets/publicguiannouncement/load_screens/vanilla_screen_renderers.json

**Comment by forthwist** [comment]
Took me an embarrassingly long time to figure out what I was supposed to do, but it was ridiculously simple once I did.  Thank you so much for the help!

**Comment by AbsolemJackdaw** [comment]
Glad you figured it out ! Ill be closing this then. Looking forward to the pack !
