### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [ArtixAllMighty/PublicGuiAnnouncement#26]

**Comment by AbsolemJackdaw** [comment]
I'm looking for people to update my mods, I'm buried in work these last months, and I got no time left.
But it's on its way !

**Comment by venaminecraft** [comment]
Hello @AbsolemJackdaw, great to hear and no rush please 😊

**Comment by venaminecraft** [comment]
Thanks for pushing the update out 😄 
I hope you go the way up to 1.20.6 in the future.
