### ISSUE TITLE
GUI has a texture bug when showing some mods

### ISSUE THREAD

**Issue by sepsol** [ArtixAllMighty/PublicGuiAnnouncement#4]
This is how it looks like:

![image](https://user-images.githubusercontent.com/47871887/67329082-37310580-f527-11e9-9f42-6a0886980bd0.png)

I saw this **bugged texture** when using:
- WorldHandler
- Better Advancements

I tried these and these were ok:
- Minecraft's pause menu
- MineMenu
- Paintings++
- opening a Minecraft chest (vanilla or from mods)
- Barrels (vanilla/mods)
- Anvils
- Ender Chest
- Enchanting Table
- Furnace
- Cartography Table
- Loom
- Smoker
- Blast Furnace
- Grindstone
- Stonecutter
- Dispensers
- Hoppers
- Droppers
- Horse Inventory
- Trader Llama's Inventory
- Brewing Stand

I see **NO** GUI at all when I'm in:
- Inventory
- Crafting Table
- [Askitor](https://www.curseforge.com/minecraft/mc-mods/astikorcarts) mod's cart inventory GUI
- [Create](https://www.curseforge.com/minecraft/mc-mods/create) mod's GUI for Schematicannon and Schematic Table
- Sign placement GUI

**CONTEXT**
I guess these from the paperdoll model on the top left. Here's my specs:
- Minecraft 1.14.4
- Forge 28.1.61
- OptiFine HD U F4 pre11
- Public GUI Announcement 1.1.0.0

**Comment by AbsolemJackdaw** [comment]
Can you provide a log please ?

**Comment by AbsolemJackdaw** [comment]
My current guess is : the texture path provided for worldhandler has some typos i it.
Same for better advancements

Create mod is currently not known to be supported.
Akitors cart inventory may not use a vanilla base for their cart gui's , so this is the same case as for Create.

Im surprised about inventory and crafting table. Did you test this with a friend or all alone ?
Its hard to get a correct angle alone sometimes.
Again, a log may help me explain these.

**Comment by sepsol** [comment]
I reported the issue to the devs of AskitorCarts and Create mod as well. Here's a log from my latest run which I triggered all of the GUIs: [latest.log](https://gist.github.com/SepSol/7234a438b6f54096a41978eeff8fc825)

I will update you if I get a chance to test this on my server.
Also, when should I send **degug.log** and when should I send **latest.log** on GitHub?! Everybody just says send the log, nobody ever specifies which one! I often get confused.

**Comment by AbsolemJackdaw** [comment]
Both are good depending on what the the dev needs to see

**Comment by AbsolemJackdaw** [comment]
I think im gonna need the dev log
Btw your latest log tells us about a network error (packets) from something called TrashSlot Network.
Its not my mod and shouldnt have too much issues on the game but the author may want to fix the spam and his code.

**Comment by sepsol** [comment]
Thank you for letting me know! I'll report that :)
Here's the [debug.log](https://gist.github.com/SepSol/64add8bba6a4e7fa7bf13ad7b880a568) for that same session.

**Comment by AbsolemJackdaw** [comment]
Well none of those helped. Theyre filled with spam from unknown packet handling of some sort.
Ill try to find the issue out myself, by manually searching the code

**Comment by sepsol** [comment]
Sorry for that! Thanks.

**Comment by AbsolemJackdaw** [comment]
Found the issue 

```
"publicguiannouncement:textures/gui/modsupport/worldhander/world_handler.png", 
```

![image](https://user-images.githubusercontent.com/3628535/67427810-2ba01600-f5dd-11e9-98ad-93335165eaea.png)
I'm missing and L in wordhandler in the json file. 

You can easily quickfix this yourself by editing the json file that is in the jar under assets/publicguiannouncement/load_screens ...

**Comment by AbsolemJackdaw** [comment]
same issue for the better advancements one. the path provided by the json is incorrect. 

I'mg going to solve these issues and PR them to the corresponding mods. It should not be up to me i.m.o to add the support, but from the mods themself

**Comment by sepsol** [comment]
owwww, i see
it feels good to fix a code with your own hands :D

**Comment by sepsol** [comment]
Thanks for the help! I'm gonna test this fix and keep you posted soon.

**Comment by AbsolemJackdaw** [comment]
cant verify anything bad for inventory or crafting table. 
they should show up

**Comment by sepsol** [comment]
I can't see the issue here though 🤔 

![image](https://user-images.githubusercontent.com/47871887/67428788-b851d080-f5eb-11e9-860e-f0d12023440e.png)

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/67429056-a79b5d80-f5df-11e9-8ba7-5cda48d34a75.png)

**Comment by AbsolemJackdaw** [comment]
its in the gui folder, not the betteradvancements folder
its nonexistent

**Comment by sepsol** [comment]
oh, yeah. I just remembered something! I'm using Aternos.org for hosting my Minecraft server. Aternos only allows to load mods that are currently on CureForge website. Will this fix work if I launch the server with the version you uploaded on curseforge and only use the fix on my clients? 🤔 I want to make sure that inventory and crafting table GUIs are working fine.

**Comment by AbsolemJackdaw** [comment]
no, the fix would only apply localy, and probably only on a single player worlds. 

you can launch the server to test the crafting and player inventory though

**Comment by AbsolemJackdaw** [comment]
it wouldn't hurt launching with a modified jar tohugh
if its only the json
chances are big they will work on your end but not on anyone elses, if they dont have the fix

**Comment by sepsol** [comment]
So here's the update:
- the fixes you told me above for **WorldHandler** and **Better Advancements** work both in singleplayer and multiplayer (even though some of the codes in mods actually mismatch, I was able to join successfully)
- The default **inventory** and **crafting tables** work too, they just don't show up on the paperdoll model - which I think may be a good thing as the paper doll model is also present in the default survival inventory.

Also I really liked that it doesn't show the creative inventory and it always defaults to showing the survival inventory :D Overall thank you very much for your time!

**Comment by AbsolemJackdaw** [comment]
yeah indeed, it has been omited in code. that is very intentional 

```
@Override
    public void render(AbstractClientPlayerEntity entityIn, float limbSwing, float limbSwingAmount, float partialTicks, float ageInTicks, float netHeadYaw, float headPitch, float scale) {

        if (Minecraft.getInstance().currentScreen instanceof InventoryScreen || Minecraft.getInstance().currentScreen instanceof CreativeScreen)
            return;

```

**Comment by sepsol** [comment]
That was genius! So if I want to not announce a GUI, all I should do is to remove their respective .json file?

**Comment by AbsolemJackdaw** [comment]
or entry yes.
the vanilla compat json has all of the entries listed. 

but ive been thinking a bit with how you did the experiment : 
The Mod loads in the jsons client side , and makes a list for the client player with all the entries. 
so it is possible you have a screen for mod X, with texture attached, and send the information to another player that does not have mod X compatibility json, and would just see a blank texture (black / pink) but that shouldn't be any nuissance really. just something that passed my mind.

**Comment by sepsol** [comment]
I used the fixed mod on one device and original mod on another device. One of them rendered those two GUIs black and pink and the other rendered them correctly.

One question: Can I only change the location of the corresponding .json files for GUIs that I don't want? I am trying to not touch the code whenever possible.

Also did you mean this .json file in the comment above?

![image](https://user-images.githubusercontent.com/47871887/67433331-c8ba7900-f5f4-11e9-8145-e77b52d75471.png)

**Comment by AbsolemJackdaw** [comment]
yes, it is that json file.

I didn't get your question all that well, but here's the deal : 
wether a screen can show up or not is determinedb y the sole presence of an entry in the json file. 

what is a screen entry ? 
its this : 
```
 {
			"class" : "net.geforcemods.securitycraft.gui.GuiCameraMonitor", 
			"texture" : "securitycraft:textures/gui/container/blank.png"
		}
```
the mod just reads trough all of them, and if any is found matching the current open screen, it will display the texture specified below. 
So you can either remove the entry ( bracket, class line, texture line, next bracket and the comma)
or replace the texture with a complete blank file. (you can put a 255x255 empty image in assets/publicguiannouncement/gui , call it empty.png, and have the "texture"  line reference that image.
it wont show up for you, and if someone else opens it, you wont be able to see it either. 
if you want an entire server to not see the screen, they need to share the same json file. 

I'd recommend https://www.curseforge.com/minecraft/mc-mods/resource-loader RESOURCE LOADER to pre load a resource for end users using a modpack, effectively replacing the same named file in a directory without people having to add a resourcepack manually. (got this mod suggested by a modpack maker)

**Comment by sepsol** [comment]
I think I got it, thanks a lot. I couldn't find any WorldHandler entried in the mensioned .json file though. Also sadly the Resource Loader mod isn't available for 1.14.4 (Forge) and it doesn't seem to get updates anymore. Otherwise I am really interested in making a modpack for my own server. It's really helpful to get newbies into the game.

I am taking your time so much, sorry for that. But I feel like I'm connected to a programming source :D three more questions and that's it:
- If I understood your message correctly that mod (Resource Loader) helps in making sure that everybody on the server is using same resourcepack and none of the clients can change that, right? If no, Is there any mod to do that? Will forcing a recourcepack from a server do the job? The reason is that I'm planning to add a mod called [Hidden Levers](https://www.curseforge.com/minecraft/mc-mods/hidden-levers) which won't do its job if textures of torches and bookshelves are changed.
- Do you know any way to save keybindings of Minecraft in one device and then transfer them to another?
- What method do you suggest for adding/removing (specially removing) recipes? For example I've got a mod called [I Like Wood](https://www.curseforge.com/minecraft/mc-mods/i-like-wood) and many of its recipes conflict with vanilla ones.

**Comment by AbsolemJackdaw** [comment]
how about you come annoy me on my discord with all those questions :D

https://discord.gg/8MEdFZh

**Comment by AbsolemJackdaw** [comment]
this issue has been resolved on discord with SepSol
