### ISSUE TITLE
1.18.1 Fabric: Not loading or being recognized by fabric(?)

### ISSUE THREAD

**Issue by Maloonkey** [ArtixAllMighty/PublicGuiAnnouncement#8]
I am noticing the textures are being loaded inside the log file but the mod itself is not anywhere in the load order.

**Comment by AbsolemJackdaw** [comment]
the mod has a mod id issue, this has been fixed in latest release. however the gui's dont seem to show up in recent testing. something with a lirbary mod not being present on build and release. 
I'm currently actively looking into it

**Comment by AbsolemJackdaw** [comment]
fixed as of release 3.1.0.2
